@isTest
public class SlowTests5 {
    
    @isTest static void testWith5SecDelay1() {
        Long startTS = System.currentTimeMillis();
        Long timeDiff = 0;
        do
        {
            timeDiff = System.currentTimeMillis() - startTS;
        }
        while(timeDiff <= 5*1000);  
        System.assertEquals(3, 3);
    }
    
    @isTest static void testWith5SecDelay2() {
        Long startTS = System.currentTimeMillis();
        Long timeDiff = 0;
        do
        {
            timeDiff = System.currentTimeMillis() - startTS;
        }
        while(timeDiff <= 5*1000);  
        System.assertEquals(3, 3);
    }
    
    @isTest static void testWith5SecDelay3() {
        Long startTS = System.currentTimeMillis();
        Long timeDiff = 0;
        do
        {
            timeDiff = System.currentTimeMillis() - startTS;
        }
        while(timeDiff <= 5*1000);  
        System.assertEquals(3, 3);
    }
    
    @isTest static void testWith5SecDelay4() {
        Long startTS = System.currentTimeMillis();
        Long timeDiff = 0;
        do
        {
            timeDiff = System.currentTimeMillis() - startTS;
        }
        while(timeDiff <= 5*1000);  
        System.assertEquals(3, 3);
    }
    
    @isTest static void testWith5SecDelay5() {
        Long startTS = System.currentTimeMillis();
        Long timeDiff = 0;
        do
        {
            timeDiff = System.currentTimeMillis() - startTS;
        }
        while(timeDiff <= 5*1000);  
        System.assertEquals(3, 3);
    }
    
    @isTest static void testWith5SecDelay6() {
        Long startTS = System.currentTimeMillis();
        Long timeDiff = 0;
        do
        {
            timeDiff = System.currentTimeMillis() - startTS;
        }
        while(timeDiff <= 5*1000);  
        System.assertEquals(3, 3);
    }
    
    @isTest static void testWith5SecDelay7() {
        Long startTS = System.currentTimeMillis();
        Long timeDiff = 0;
        do
        {
            timeDiff = System.currentTimeMillis() - startTS;
        }
        while(timeDiff <= 5*1000);  
        System.assertEquals(3, 3);
    }
    
    @isTest static void testWith5SecDelay8() {
        Long startTS = System.currentTimeMillis();
        Long timeDiff = 0;
        do
        {
            timeDiff = System.currentTimeMillis() - startTS;
        }
        while(timeDiff <= 5*1000);  
        System.assertEquals(3, 3);
    }
    
    @isTest static void testWith5SecDelay9() {
        Long startTS = System.currentTimeMillis();
        Long timeDiff = 0;
        do
        {
            timeDiff = System.currentTimeMillis() - startTS;
        }
        while(timeDiff <= 5*1000);  
        System.assertEquals(3, 3);
    }
    @isTest static void testWith5SecDelay10() {
        Long startTS = System.currentTimeMillis();
        Long timeDiff = 0;
        do
        {
            timeDiff = System.currentTimeMillis() - startTS;
        }
        while(timeDiff <= 5*1000);  
        System.assertEquals(3, 3);
    }
}